### ISSUE TITLE
Build frontend and backend in parallel in CI

### ISSUE THREAD

**Issue by Gelio** [Gelio/CAL-web#2]
Backend and frontend can be built in parallel in GitHub Actions. After they are built, frontend assets could be copied into the built JAR by:

1. Building only the `sirius-web-frontend` JAR
2. Copying it into the `sirius-web-sample-application` JAR directly by using https://stackoverflow.com/a/14388993/4874344

This should speed up the CI by about 2x, since the two jobs that run sequentially ATM each take around 2 minutes. If they run in parallel, they will take 2 mins each, and then there will be another short job to integrate the results.

**Comment by Gelio** [comment]
When trying to do that naively:

```sh
zip -r staging/sirius-web-application.jar BOOT-INF/lib
```

(`BOOT-INF/lib` contains `sirius-web-frontend-0.5.0.jar` with frontend assets inside)

there is the following exception when starting the application:

```
19:13 $ java -jar staging/sirius-web-application.jar --spring.profiles.active=dev
Exception in thread "main" java.lang.IllegalStateException: Failed to get nested archive for entry BOOT-INF/lib/sirius-web-frontend-0.5.0.jar
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:120)
        at org.springframework.boot.loader.archive.JarFileArchive$NestedArchiveIterator.adapt(JarFileArchive.java:274)
        at org.springframework.boot.loader.archive.JarFileArchive$NestedArchiveIterator.adapt(JarFileArchive.java:265)
        at org.springframework.boot.loader.archive.JarFileArchive$AbstractIterator.next(JarFileArchive.java:226)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.createClassLoader(ExecutableArchiveLauncher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:55)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.io.IOException: Unable to open nested jar file 'BOOT-INF/lib/sirius-web-frontend-0.5.0.jar'
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:306)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:292)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:116)
        ... 6 more
Caused by: java.lang.IllegalStateException: Unable to open nested entry 'BOOT-INF/lib/sirius-web-frontend-0.5.0.jar'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:332)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:314)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:303)
        ... 8 more
```

**Comment by Gelio** [comment]
Using `--compression-method=store` when injecting the JAR into the main JAR did the trick:

```sh
zip -r --compression-method=store staging/sirius-web-application.jar BOOT-INF/lib
```
