### ISSUE TITLE
Backend endpoint to add a BalticLSC Toolbox entry to the model

### ISSUE THREAD

**Issue by Gelio** [Gelio/CAL-web#32]
Following the investigation done in https://github.com/Gelio/CAL-web/issues/12#issuecomment-964489163, let's create a Spring controller that would get a BalticLSC Toolbox entry (already fetched in #11) and an `editingContextId`. It would find the model, create a new `UnitCall` to it and optionally create a new `ComputationUnitRelease` too.

If possible, try to make it a new GraphQL mutation that hooks into existing Sirius Web mutations, instead of a Spring controller. This way the whole application could stay within GraphQL to communicate within Sirius.

## Example Toolbox entries

<details>
<summary>ComputationModuleRelease</summary>

```json
{
  "image": "",
  "command": "",
  "commandArguments": [],
  "variableMappings": [],
  "requiredServices": [],
  "unit": {
    "name": "Bounding Labels",
    "uid": "4c4b9120-9cc6-414a-b5e7-4254d451d76b",
    "pClass": null,
    "shortDescription": null,
    "longDescription": null,
    "keywords": null,
    "icon": "https://www.balticlsc.eu/model/_icons/default.png",
    "isApp": false,
    "isService": false
  },
  "version": "0.11",
  "uid": "110f65c2-3fc6-411c-9ded-8c8cf96db52d",
  "status": 0,
  "date": "2021-09-30T19:01:28.379053",
  "description": "Bounding Labels0.11",
  "openSource": false,
  "usageCounter": 0,
  "pins": [
    {
      "uid": "c915d7a5-dec5-4b60-9fdb-00eed6591cc4",
      "name": "Input",
      "binding": 0,
      "tokenMultiplicity": 0,
      "dataMultiplicity": 0,
      "dataTypeUid": "dd-003-002",
      "dataTypeName": "PNG",
      "dataStructureUid": null,
      "dataStructureName": null,
      "accessTypeUid": "dd-004-001",
      "accessTypeName": "MongoDB"
    },
    {
      "uid": "76c05ac4-4b34-4053-97e5-8d65748d1485",
      "name": "Output",
      "binding": 2,
      "tokenMultiplicity": 0,
      "dataMultiplicity": 0,
      "dataTypeUid": "dd-003-002",
      "dataTypeName": "PNG",
      "dataStructureUid": null,
      "dataStructureName": null,
      "accessTypeUid": "dd-004-001",
      "accessTypeName": "MongoDB"
    }
  ],
  "supportedResourcesRange": {
    "minCPUs": -1,
    "minGPUs": -1,
    "minMemory": -1,
    "minStorage": -1,
    "maxCPUs": -1,
    "maxGPUs": -1,
    "maxMemory": -1,
    "maxStorage": -1
  }
}
```

</details>

<details>
<summary>ComputationApplicationRelease</summary>

```json
{
  "diagramUid": "bd37887e-3c8d-49d4-9988-fd06a1f8eaa8",
  "unit": {
    "name": "Distance Matrix Calculator",
    "uid": "6d0be02e-4860-45cd-8cde-0d766feefa48",
    "pClass": null,
    "shortDescription": "Finds all distances between given addresses using user-provided map",
    "longDescription": null,
    "keywords": null,
    "icon": "https://www.balticlsc.eu/model/_icons/default.png",
    "isApp": true,
    "isService": false
  },
  "version": "v0.1",
  "uid": "12f8248a-fc17-48f6-8305-f5f85cfdfaf6",
  "status": 0,
  "date": "2021-10-22T10:47:45.686311",
  "description": null,
  "openSource": false,
  "usageCounter": 0,
  "pins": [
    {
      "uid": "c28002b5-af5f-4665-83b7-319151219171",
      "name": "Geo Objects",
      "binding": 0,
      "tokenMultiplicity": 0,
      "dataMultiplicity": 0,
      "dataTypeUid": "dd-001-001",
      "dataTypeName": "JSON",
      "dataStructureUid": null,
      "dataStructureName": null,
      "accessTypeUid": "dd-006-000",
      "accessTypeName": "FTP"
    },
    {
      "uid": "57dc55d7-dc7e-4a24-9a9f-ea9b99ac35e7",
      "name": "Map",
      "binding": 0,
      "tokenMultiplicity": 0,
      "dataMultiplicity": 0,
      "dataTypeUid": "dd-001-000",
      "dataTypeName": "DataFile",
      "dataStructureUid": null,
      "dataStructureName": null,
      "accessTypeUid": "dd-006-000",
      "accessTypeName": "FTP"
    },
    {
      "uid": "6c38bfcb-a498-4a7e-b745-000655ed2680",
      "name": "Matrix",
      "binding": 2,
      "tokenMultiplicity": 0,
      "dataMultiplicity": 0,
      "dataTypeUid": "dd-001-001",
      "dataTypeName": "JSON",
      "dataStructureUid": null,
      "dataStructureName": null,
      "accessTypeUid": "dd-006-000",
      "accessTypeName": "FTP"
    }
  ],
  "supportedResourcesRange": {
    "minCPUs": 0,
    "minGPUs": 0,
    "minMemory": 0,
    "minStorage": 0,
    "maxCPUs": 0,
    "maxGPUs": 0,
    "maxMemory": 0,
    "maxStorage": 0
  }
}
```

</details>

## Tasklist

- [x] Add a DTO for `ComputationUnitRelease`
- [ ] Add a new mutation that retrieves it along with the editing context ID
    - [ ] Add the `ComputationUnitRelease` to the model
    - [ ] Detect if the `ComputationUnitRelease` is already in the model. If yes, skip adding it
    - [ ] Add a `UnitCall` to the model

## Depends on

- [ ] https://github.com/Gelio/CAL-web/issues/16 (not sure, to be investigated)

**Comment by Gelio** [comment]
To modify the model live we need to hook into the _change detection_ of Sirius Web.

I believe the easiest thing to do would be to simulate calling the `createChild` mutation over and over. It handles adding objects to the diagram and emits `ChangeDescription` objects:

https://github.com/eclipse-sirius/sirius-components/blob/master/backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/CreateChildEventHandler.java

For reading the model after a change was made we would need to use the `IObjectService`, similarly to:

https://github.com/eclipse-sirius/sirius-components/blob/ab8097c6c3593f10fdd16f9212762624a3639ccc/backend/sirius-web-spring-collaborative/src/main/java/org/eclipse/sirius/web/spring/collaborative/handlers/CreateChildEventHandler.java#L84-L86

For an implementation of a mutation in Sirius Web, see https://github.com/Gelio/CAL-web/blob/f9853f45231a40883c79be9a0e65bbb5dce731c3/backend/sirius-web-graphql/src/main/java/org/eclipse/sirius/web/graphql/datafetchers/mutation/MutationCreateChildDataFetcher.java#L74-L83

**Comment by Gelio** [comment]
Doing the following:

```java
            var createChildInput = (CreateUnitCallInput) input;
            // NOTE: hardcode the representation ID for now
            var object = this.objectService.getObject(editingContext, createChildInput.getHowToCallYou());

            if (object.isPresent() && ComputationApplicationRelease.class.isInstance(object.get())) {
                var root = (ComputationApplicationRelease) object.get();
                var call = CALFactory.eINSTANCE.createUnitCall();
                root.getCalls().add(call);
                call.setName("Auto gen"); //$NON-NLS-1$
                var pin = CALFactory.eINSTANCE.createComputedDataPin();
                call.getPins().add(pin);
                changeDescription = new ChangeDescription(ChangeKind.SEMANTIC_CHANGE, editingContext.getId(), input);
            }
```

Can create a few objects (2 in my case), but after I create 1 more, the diagram cannot be loaded and I get the following error in the terminal:

```
Caused by: graphql.execution.NonNullableFieldWasNullException: The field at path '/diagramEvent/diagram/nodes[1]/position/x' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'Float' within parent type 'Position'
        at graphql.execution.NonNullableFieldValidator.validate(NonNullableFieldValidator.java:49) ~[graphql-java-17.1.jar!/:na]
        at graphql.execution.ExecutionStrategy.completeValueForScalar(ExecutionStrategy.java:606) ~[graphql-java-17.1.jar!/:na]
        at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:446) ~[graphql-java-17.1.jar!/:na]
        at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:409) ~[graphql-java-17.1.jar!/:na]
        at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:212) ~[graphql-java-17.1.jar!/:na]
        at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094) ~[na:na]
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:211) ~[graphql-java-17.1.jar!/:na]
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60) ~[graphql-java-17.1.jar!/:na]
        ... 76 common frames omitted
```

This is probably because just modifying the metamodel does not create diagram nodes.

Looks like modifying the model won't be as easy as I thought. We need to use `EditService` to modify the model. This also changes the representations in necessary ways:

```java
                var root = (ComputationApplicationRelease) object.get();
                // // @formatter:off
                var creationDescription = this.editService.getChildCreationDescriptions(editingContext.getId(), "CAL::ComputationApplicationRelease") //$NON-NLS-1$
                    .stream()
                    .filter(c -> c.getLabel().contains("Unit Release")) //$NON-NLS-1$
                    .findFirst();
                // @formatter:on
                creationDescription.flatMap(d -> this.editService.createChild(editingContext, root, d.getId())).map(ComputationUnitRelease.class::cast).ifPresent(x -> {
                    x.setName("Auto gen"); //$NON-NLS-1$
                    this.editService.getChildCreationDescriptions(editingContext.getId(), "CAL::ComputationUnitRelease") //$NON-NLS-1$
                            .stream().filter(c -> c.getLabel().contains("Declared Data Pin")) //$NON-NLS-1$
                            .findFirst().flatMap(d -> this.editService.createChild(editingContext, x, d.getId())).map(DeclaredDataPin.class::cast).ifPresent(pin -> {
                                pin.setName("Auto generated pin"); //$NON-NLS-1$
                            });

                });
                changeDescription = new ChangeDescription(ChangeKind.SEMANTIC_CHANGE, editingContext.getId(), input);
```

This way I can create however many objects I want without errors.
